name: cargoshuttle
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.18.0
  flutter_datetime_formfield: ^0.1.2
  string_validator: ^0.1.4
  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_admin: ^0.1.3
  cloud_firestore: ^0.13.7
  modal_progress_hud: ^0.1.3
  email_validator: ^1.0.5
  shared_preferences: ^0.5.12
  firebase: ^7.3.0
  fluttertoast: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:

    - family: Arbutus Slab
      fonts:
        - asset: assets/fonts/ArbutusSlab-Regular.ttf

    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf